import { Buffer } from "buffer";
import { ethers } from "ethers";
import scryptJS from "scrypt-js";
import { nanoid } from "nanoid";
import { TronWeb } from "tronweb";
import zxcvbn from "zxcvbn";

const { scrypt } = scryptJS;
const abi = new ethers.AbiCoder();

const HASH_OPTIONS = {
  N: 32768, // CPU/memory cost parameter, 2^15
  r: 8, // block size parameter
  p: 5, // parallelization parameter
  keyLen: 64,
};

/**
 * This function computes the scrypt hash using provided passphrase and pin inputs.
 * Passphrase and pin are validated with zxcvbn; weak values are rejected (returns "").
 *
 * @param {*} passphrase - Must have zxcvbn score >= 3
 * @param {*} pin - Must have zxcvbn score >= 1
 * @param {*} cb a callback function designed to receive the progress updates during the scrypt hashing process.
 * @returns hash result as string format, or "" if passphrase/pin missing or too weak
 */
export async function generateHash(passphrase, pin, cb = () => {}) {
  if (!passphrase || !pin) {
    return "";
  }

  const passphraseResult = zxcvbn(passphrase);
  if (passphraseResult.score < 3) {
    return "";
  }

  const pinResult = zxcvbn(pin);
  if (pinResult.score < 1) {
    return "";
  }

  const salt = `${passphrase.slice(-4)}${pin}`;

  const passwordBuffer = Buffer.from(passphrase);
  const saltBuffer = Buffer.from(salt);

  const hashBuffer = await scrypt(
    passwordBuffer,
    saltBuffer,
    HASH_OPTIONS.N,
    HASH_OPTIONS.r,
    HASH_OPTIONS.p,
    HASH_OPTIONS.keyLen,
    cb
  );

  return Buffer.from(hashBuffer).toString("hex");
}

/**
 * This function derives the EVM private key from a result of the scrypt hash.
 * @param {*} hash scrypt hash result
 * @returns private key as string format
 */
export function getEvmPrivateKey(hash) {
  return ethers.keccak256(abi.encode(["string"], [hash]));
}

/**
 * This function returns the EVM wallet address from a result of the scrypt hash.
 * @param {*} hash scrypt hash result
 * @returns address as string format
 */
export function getEvmWalletAddress(hash) {
  const privateKey = getEvmPrivateKey(hash);
  const wallet = new ethers.Wallet(privateKey);
  return wallet.address;
}

/**
 * This function returns the TRON wallet address from a result of the scrypt hash.
 * @param {*} hash scrypt hash result
 * @returns address as string format
 */
export function getTronWalletAddress(hash) {
  const privateKey = getEvmPrivateKey(hash);
  return TronWeb.address.fromPrivateKey(privateKey.slice(2));
}

const URL_DELIMITER = "\u0002";
const NETWORKS = [
  "ethereum",
  "polygon",
  "arbitrum",
  "optimism",
  "bsc",
  "avalanche",
  "base",
  "tron",
];
/**
 * This function generates a transfer-link token by encoding passphrase and PIN by Base64 and adding random padding.
 * The transfer-link enables users to send their full ownership of a wallet account to another user for gifting or airdropping.
 * Passphrase and PIN are validated with zxcvbn; weak values are rejected (returns null).
 *
 * @param {*} passphrase - Must have zxcvbn score >= 3
 * @param {*} PIN - Must have zxcvbn score >= 1
 * @param {*} network ethereum | polygon | arbitrum | optimism | bsc | avalanche | base | tron
 * @returns A string formatted as a transfer-link token, which can be appended to `https://app.mybucks.online#wallet=`, or null if invalid/weak
 */
export function generateToken(passphrase, pin, network) {
  if (!passphrase || !pin || !network) {
    return null;
  }
  if (!NETWORKS.find((n) => n === network)) {
    return null;
  }

  if (zxcvbn(passphrase).score < 3) {
    return null;
  }
  if (zxcvbn(pin).score < 1) {
    return null;
  }

  const merged = Buffer.from(
    passphrase + URL_DELIMITER + pin + URL_DELIMITER + network,
    "utf-8"
  );
  const base64Encoded = merged.toString("base64");
  const padding = nanoid(12);
  return padding.slice(0, 6) + base64Encoded + padding.slice(6);
}

/**
 * This function parses a transfer-link token generated by generateToken().
 * @param {*} token
 * @returns an array of strings, including the passphrase, pin and network.
 */
export function parseToken(token) {
  const payload = token.slice(6, token.length - 6);
  const base64Decoded = Buffer.from(payload, "base64").toString("utf-8");
  const [passphrase, pin, network] = base64Decoded.split(URL_DELIMITER);
  return [passphrase, pin, network];
}
