import { Buffer } from "buffer";
import { nanoid } from "nanoid";
import zxcvbn from "zxcvbn";
import {
  PASSPHRASE_MIN_LENGTH,
  PASSPHRASE_MAX_LENGTH,
  PIN_MIN_LENGTH,
  PIN_MAX_LENGTH,
} from "./credentials.js";

const URL_DELIMITER = "\u0002";
// Version byte for the default (non-legacy) token format.
// Uses a compact length-prefixed encoding for passphrase, pin and network.
const TOKEN_VERSION_COMPACT = 0x02;

const NETWORKS = [
  "ethereum",
  "polygon",
  "arbitrum",
  "optimism",
  "bsc",
  "avalanche",
  "base",
  "tron",
];

/**
 * This function generates a transfer-link token by encoding passphrase, pin and network, and adding random padding.
 * The transfer-link enables users to send their full ownership of a wallet account to another user for gifting or airdropping.
 * Passphrase and PIN are validated by length (see PASSPHRASE_MIN/MAX_LENGTH, PIN_MIN/MAX_LENGTH) and zxcvbn; invalid or weak values are rejected (returns null).
 * When legacy is false, payload is compact length-prefixed (version 0x02) to avoid concatenation ambiguity and keep the URL fragment short; when true, uses URL_DELIMITER concatenation.
 *
 * @param {string} passphrase - Length in [PASSPHRASE_MIN_LENGTH, PASSPHRASE_MAX_LENGTH], zxcvbn score >= 3
 * @param {string} pin - Length in [PIN_MIN_LENGTH, PIN_MAX_LENGTH], zxcvbn score >= 1
 * @param {string} network - ethereum | polygon | arbitrum | optimism | bsc | avalanche | base | tron
 * @param {boolean} legacy - when true, use URL_DELIMITER concatenation; when false, use compact length-prefixed encoding for the payload
 * @returns A string formatted as a transfer-link token, which can be appended to `https://app.mybucks.online#wallet=`, or null if invalid/weak
 */
export function generateToken(passphrase, pin, network, legacy = false) {
  if (!passphrase || !pin || !network) {
    return null;
  }
  if (!NETWORKS.find((n) => n === network)) {
    return null;
  }

  const passphraseLen = passphrase.length;
  if (
    passphraseLen < PASSPHRASE_MIN_LENGTH ||
    passphraseLen > PASSPHRASE_MAX_LENGTH
  ) {
    return null;
  }

  const pinLen = pin.length;
  if (pinLen < PIN_MIN_LENGTH || pinLen > PIN_MAX_LENGTH) {
    return null;
  }

  if (zxcvbn(passphrase).score < 3) {
    return null;
  }
  if (zxcvbn(pin).score < 1) {
    return null;
  }

  let payloadBuffer;
  if (legacy) {
    payloadBuffer = Buffer.from(
      passphrase + URL_DELIMITER + pin + URL_DELIMITER + network,
      "utf-8",
    );
  } else {
    // Default format: compact length-prefixed encoding.
    const passphraseBytes = Buffer.from(passphrase, "utf-8");
    const pinBytes = Buffer.from(pin, "utf-8");
    const networkBytes = Buffer.from(network, "utf-8");

    payloadBuffer = Buffer.concat([
      Buffer.from([TOKEN_VERSION_COMPACT]),
      Buffer.from([passphraseBytes.length]),
      passphraseBytes,
      Buffer.from([pinBytes.length]),
      pinBytes,
      Buffer.from([networkBytes.length]),
      networkBytes,
    ]);
  }

  const base64Encoded = payloadBuffer.toString("base64");
  const padding = nanoid(12);
  return padding.slice(0, 6) + base64Encoded + padding.slice(6);
}

/**
 * This function parses a transfer-link token generated by generateToken().
 * Tokens whose payload starts with 0x02 are decoded as compact length-prefixed; otherwise payload is treated as legacy (UTF-8 + URL_DELIMITER).
 * @param {string} token - token string returned by generateToken()
 * @returns {[string, string, string, boolean]} [passphrase, pin, network, legacy] - legacy is true if token was in legacy format, false if compact-encoded
 */
export function parseToken(token) {
  const payload = token.slice(6, token.length - 6);
  const decoded = Buffer.from(payload, "base64");

  if (decoded[0] === TOKEN_VERSION_COMPACT) {
    let i = 1;
    const lenP = decoded[i++];
    const passphrase = decoded.subarray(i, i + lenP).toString("utf-8");
    i += lenP;
    const lenI = decoded[i++];
    const pin = decoded.subarray(i, i + lenI).toString("utf-8");
    i += lenI;
    const lenN = decoded[i++];
    const network = decoded.subarray(i, i + lenN).toString("utf-8");
    return [passphrase, pin, network, false];
  }
  const str = decoded.toString("utf-8");
  const [passphrase, pin, network] = str.split(URL_DELIMITER);
  return [passphrase, pin, network, true];
}
